baseURL = "https://bavlynady.github.io/"
languageCode = "en-us"
title = "Bavly Nady"


[params]
  author = "Bavly Nady"
  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# config.toml
[build]
  ignoreFiles = ["\\.tmp$", "\\.bak$"]
